ERROR: file or directory not found: ./DYNAMOSA/test_stack5_DYNAMOSA.py

============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/auri/temp/lucca/python_experiments/stack5
collected 0 items

============================ no tests ran in 0.00s =============================
